/*
 * Hub Token
 * Generate Token
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for CustomAttributeDTO
 */
public class CustomAttributeDTOTest {
    private final CustomAttributeDTO model = new CustomAttributeDTO();

    /**
     * Model tests for CustomAttributeDTO
     */
    @Test
    public void testCustomAttributeDTO() {
        // TODO: test CustomAttributeDTO
    }

    /**
     * Test the property 'customAttributeId'
     */
    @Test
    public void customAttributeIdTest() {
        // TODO: test customAttributeId
    }

    /**
     * Test the property 'entityType'
     */
    @Test
    public void entityTypeTest() {
        // TODO: test entityType
    }

    /**
     * Test the property 'toolId'
     */
    @Test
    public void toolIdTest() {
        // TODO: test toolId
    }

    /**
     * Test the property 'customAttributeName'
     */
    @Test
    public void customAttributeNameTest() {
        // TODO: test customAttributeName
    }

    /**
     * Test the property 'attributeType'
     */
    @Test
    public void attributeTypeTest() {
        // TODO: test attributeType
    }

    /**
     * Test the property 'options'
     */
    @Test
    public void optionsTest() {
        // TODO: test options
    }

    /**
     * Test the property 'checked'
     */
    @Test
    public void checkedTest() {
        // TODO: test checked
    }

    /**
     * Test the property 'required'
     */
    @Test
    public void requiredTest() {
        // TODO: test required
    }

}
