/*
 * Hub Token
 * Generate Token
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ReminderDTO
 */
public class ReminderDTOTest {
    private final ReminderDTO model = new ReminderDTO();

    /**
     * Model tests for ReminderDTO
     */
    @Test
    public void testReminderDTO() {
        // TODO: test ReminderDTO
    }

    /**
     * Test the property 'reminderType'
     */
    @Test
    public void reminderTypeTest() {
        // TODO: test reminderType
    }

    /**
     * Test the property 'schedulingInterval'
     */
    @Test
    public void schedulingIntervalTest() {
        // TODO: test schedulingInterval
    }

    /**
     * Test the property 'timeUnit'
     */
    @Test
    public void timeUnitTest() {
        // TODO: test timeUnit
    }

    /**
     * Test the property 'modes'
     */
    @Test
    public void modesTest() {
        // TODO: test modes
    }

}
