/*
 * Hub Token
 * Generate Token
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for UdfDTO
 */
public class UdfDTOTest {
    private final UdfDTO model = new UdfDTO();

    /**
     * Model tests for UdfDTO
     */
    @Test
    public void testUdfDTO() {
        // TODO: test UdfDTO
    }

    /**
     * Test the property 'udf1'
     */
    @Test
    public void udf1Test() {
        // TODO: test udf1
    }

    /**
     * Test the property 'udf2'
     */
    @Test
    public void udf2Test() {
        // TODO: test udf2
    }

    /**
     * Test the property 'udf3'
     */
    @Test
    public void udf3Test() {
        // TODO: test udf3
    }

    /**
     * Test the property 'udf4'
     */
    @Test
    public void udf4Test() {
        // TODO: test udf4
    }

    /**
     * Test the property 'udf5'
     */
    @Test
    public void udf5Test() {
        // TODO: test udf5
    }

}
