/*
 * Hub Token
 * Generate Token
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * CustomAttributeDTO
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-06-07T19:17:40.573+05:30[Asia/Kolkata]")
public class CustomAttributeDTO {
  public static final String SERIALIZED_NAME_CUSTOM_ATTRIBUTE_ID = "customAttributeId";
  @SerializedName(SERIALIZED_NAME_CUSTOM_ATTRIBUTE_ID)
  private Integer customAttributeId;

  public static final String SERIALIZED_NAME_ENTITY_TYPE = "entityType";
  @SerializedName(SERIALIZED_NAME_ENTITY_TYPE)
  private String entityType;

  public static final String SERIALIZED_NAME_TOOL_ID = "toolId";
  @SerializedName(SERIALIZED_NAME_TOOL_ID)
  private Integer toolId;

  public static final String SERIALIZED_NAME_CUSTOM_ATTRIBUTE_NAME = "customAttributeName";
  @SerializedName(SERIALIZED_NAME_CUSTOM_ATTRIBUTE_NAME)
  private String customAttributeName;

  public static final String SERIALIZED_NAME_ATTRIBUTE_TYPE = "attributeType";
  @SerializedName(SERIALIZED_NAME_ATTRIBUTE_TYPE)
  private String attributeType;

  public static final String SERIALIZED_NAME_OPTIONS = "options";
  @SerializedName(SERIALIZED_NAME_OPTIONS)
  private List<String> options = null;

  public static final String SERIALIZED_NAME_CHECKED = "checked";
  @SerializedName(SERIALIZED_NAME_CHECKED)
  private Boolean checked;

  public static final String SERIALIZED_NAME_REQUIRED = "required";
  @SerializedName(SERIALIZED_NAME_REQUIRED)
  private Boolean required;


  public CustomAttributeDTO customAttributeId(Integer customAttributeId) {
    
    this.customAttributeId = customAttributeId;
    return this;
  }

   /**
   * Get customAttributeId
   * @return customAttributeId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getCustomAttributeId() {
    return customAttributeId;
  }


  public void setCustomAttributeId(Integer customAttributeId) {
    this.customAttributeId = customAttributeId;
  }


  public CustomAttributeDTO entityType(String entityType) {
    
    this.entityType = entityType;
    return this;
  }

   /**
   * Get entityType
   * @return entityType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getEntityType() {
    return entityType;
  }


  public void setEntityType(String entityType) {
    this.entityType = entityType;
  }


  public CustomAttributeDTO toolId(Integer toolId) {
    
    this.toolId = toolId;
    return this;
  }

   /**
   * Get toolId
   * @return toolId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getToolId() {
    return toolId;
  }


  public void setToolId(Integer toolId) {
    this.toolId = toolId;
  }


  public CustomAttributeDTO customAttributeName(String customAttributeName) {
    
    this.customAttributeName = customAttributeName;
    return this;
  }

   /**
   * Get customAttributeName
   * @return customAttributeName
  **/
  @ApiModelProperty(required = true, value = "")

  public String getCustomAttributeName() {
    return customAttributeName;
  }


  public void setCustomAttributeName(String customAttributeName) {
    this.customAttributeName = customAttributeName;
  }


  public CustomAttributeDTO attributeType(String attributeType) {
    
    this.attributeType = attributeType;
    return this;
  }

   /**
   * Get attributeType
   * @return attributeType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getAttributeType() {
    return attributeType;
  }


  public void setAttributeType(String attributeType) {
    this.attributeType = attributeType;
  }


  public CustomAttributeDTO options(List<String> options) {
    
    this.options = options;
    return this;
  }

  public CustomAttributeDTO addOptionsItem(String optionsItem) {
    if (this.options == null) {
      this.options = new ArrayList<String>();
    }
    this.options.add(optionsItem);
    return this;
  }

   /**
   * Get options
   * @return options
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getOptions() {
    return options;
  }


  public void setOptions(List<String> options) {
    this.options = options;
  }


  public CustomAttributeDTO checked(Boolean checked) {
    
    this.checked = checked;
    return this;
  }

   /**
   * Get checked
   * @return checked
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getChecked() {
    return checked;
  }


  public void setChecked(Boolean checked) {
    this.checked = checked;
  }


  public CustomAttributeDTO required(Boolean required) {
    
    this.required = required;
    return this;
  }

   /**
   * Get required
   * @return required
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getRequired() {
    return required;
  }


  public void setRequired(Boolean required) {
    this.required = required;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomAttributeDTO customAttributeDTO = (CustomAttributeDTO) o;
    return Objects.equals(this.customAttributeId, customAttributeDTO.customAttributeId) &&
        Objects.equals(this.entityType, customAttributeDTO.entityType) &&
        Objects.equals(this.toolId, customAttributeDTO.toolId) &&
        Objects.equals(this.customAttributeName, customAttributeDTO.customAttributeName) &&
        Objects.equals(this.attributeType, customAttributeDTO.attributeType) &&
        Objects.equals(this.options, customAttributeDTO.options) &&
        Objects.equals(this.checked, customAttributeDTO.checked) &&
        Objects.equals(this.required, customAttributeDTO.required);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customAttributeId, entityType, toolId, customAttributeName, attributeType, options, checked, required);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomAttributeDTO {\n");
    sb.append("    customAttributeId: ").append(toIndentedString(customAttributeId)).append("\n");
    sb.append("    entityType: ").append(toIndentedString(entityType)).append("\n");
    sb.append("    toolId: ").append(toIndentedString(toolId)).append("\n");
    sb.append("    customAttributeName: ").append(toIndentedString(customAttributeName)).append("\n");
    sb.append("    attributeType: ").append(toIndentedString(attributeType)).append("\n");
    sb.append("    options: ").append(toIndentedString(options)).append("\n");
    sb.append("    checked: ").append(toIndentedString(checked)).append("\n");
    sb.append("    required: ").append(toIndentedString(required)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

