/*
 * Hub Token
 * Generate Token
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.AddressDTO;
import org.openapitools.client.model.CustomAttributeDTO;
import org.openapitools.client.model.CustomerDTO;
import org.openapitools.client.model.ReminderDTO;
import org.openapitools.client.model.UdfDTO;

/**
 * PaymentLinkRequestDTO
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-06-07T19:17:40.573+05:30[Asia/Kolkata]")
public class PaymentLinkRequestDTO {
  public static final String SERIALIZED_NAME_INVOICE_NUMBER = "invoiceNumber";
  @SerializedName(SERIALIZED_NAME_INVOICE_NUMBER)
  private String invoiceNumber;

  public static final String SERIALIZED_NAME_IS_AMOUNT_FILLED_BY_CUSTOMER = "isAmountFilledByCustomer";
  @SerializedName(SERIALIZED_NAME_IS_AMOUNT_FILLED_BY_CUSTOMER)
  private Boolean isAmountFilledByCustomer;

  public static final String SERIALIZED_NAME_SUB_AMOUNT = "subAmount";
  @SerializedName(SERIALIZED_NAME_SUB_AMOUNT)
  private Double subAmount;

  public static final String SERIALIZED_NAME_TAX = "tax";
  @SerializedName(SERIALIZED_NAME_TAX)
  private Double tax;

  public static final String SERIALIZED_NAME_SHIPPING_CHARGE = "shippingCharge";
  @SerializedName(SERIALIZED_NAME_SHIPPING_CHARGE)
  private Double shippingCharge;

  public static final String SERIALIZED_NAME_MIN_AMOUNT_FOR_CUSTOMER = "minAmountForCustomer";
  @SerializedName(SERIALIZED_NAME_MIN_AMOUNT_FOR_CUSTOMER)
  private Double minAmountForCustomer;

  public static final String SERIALIZED_NAME_DISCOUNT = "discount";
  @SerializedName(SERIALIZED_NAME_DISCOUNT)
  private Double discount;

  public static final String SERIALIZED_NAME_ADJUSTMENT = "adjustment";
  @SerializedName(SERIALIZED_NAME_ADJUSTMENT)
  private Double adjustment;

  public static final String SERIALIZED_NAME_SMS_CONFIRM = "smsConfirm";
  @SerializedName(SERIALIZED_NAME_SMS_CONFIRM)
  private String smsConfirm;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_SOURCE = "source";
  @SerializedName(SERIALIZED_NAME_SOURCE)
  private String source;

  public static final String SERIALIZED_NAME_IS_PARTIAL_PAYMENT_ALLOWED = "isPartialPaymentAllowed";
  @SerializedName(SERIALIZED_NAME_IS_PARTIAL_PAYMENT_ALLOWED)
  private Boolean isPartialPaymentAllowed;

  public static final String SERIALIZED_NAME_CURRENCY = "currency";
  @SerializedName(SERIALIZED_NAME_CURRENCY)
  private String currency;

  public static final String SERIALIZED_NAME_MAX_PAYMENTS_ALLOWED = "maxPaymentsAllowed";
  @SerializedName(SERIALIZED_NAME_MAX_PAYMENTS_ALLOWED)
  private Integer maxPaymentsAllowed;

  public static final String SERIALIZED_NAME_BATCH_ID = "batchId";
  @SerializedName(SERIALIZED_NAME_BATCH_ID)
  private String batchId;

  public static final String SERIALIZED_NAME_EXPIRY_DATE = "expiryDate";
  @SerializedName(SERIALIZED_NAME_EXPIRY_DATE)
  private String expiryDate;

  public static final String SERIALIZED_NAME_SCHEDULED_FOR = "scheduledFor";
  @SerializedName(SERIALIZED_NAME_SCHEDULED_FOR)
  private String scheduledFor;

  public static final String SERIALIZED_NAME_VIA_EMAIL = "viaEmail";
  @SerializedName(SERIALIZED_NAME_VIA_EMAIL)
  private Boolean viaEmail;

  public static final String SERIALIZED_NAME_VIA_SMS = "viaSms";
  @SerializedName(SERIALIZED_NAME_VIA_SMS)
  private Boolean viaSms;

  public static final String SERIALIZED_NAME_CUSTOMER = "customer";
  @SerializedName(SERIALIZED_NAME_CUSTOMER)
  private CustomerDTO customer;

  public static final String SERIALIZED_NAME_UDF = "udf";
  @SerializedName(SERIALIZED_NAME_UDF)
  private UdfDTO udf;

  public static final String SERIALIZED_NAME_ADDRESS = "address";
  @SerializedName(SERIALIZED_NAME_ADDRESS)
  private AddressDTO address;

  public static final String SERIALIZED_NAME_EMAIL_TEMPLATE_NAME = "emailTemplateName";
  @SerializedName(SERIALIZED_NAME_EMAIL_TEMPLATE_NAME)
  private String emailTemplateName;

  public static final String SERIALIZED_NAME_SMS_TEMPLATE_NAME = "smsTemplateName";
  @SerializedName(SERIALIZED_NAME_SMS_TEMPLATE_NAME)
  private String smsTemplateName;

  public static final String SERIALIZED_NAME_VALIDATION_PERIOD = "validationPeriod";
  @SerializedName(SERIALIZED_NAME_VALIDATION_PERIOD)
  private String validationPeriod;

  public static final String SERIALIZED_NAME_TIME_UNIT = "timeUnit";
  @SerializedName(SERIALIZED_NAME_TIME_UNIT)
  private String timeUnit;

  public static final String SERIALIZED_NAME_NOTES = "notes";
  @SerializedName(SERIALIZED_NAME_NOTES)
  private String notes;

  public static final String SERIALIZED_NAME_SUCCESS_U_R_L = "successURL";
  @SerializedName(SERIALIZED_NAME_SUCCESS_U_R_L)
  private String successURL;

  public static final String SERIALIZED_NAME_FAILURE_U_R_L = "failureURL";
  @SerializedName(SERIALIZED_NAME_FAILURE_U_R_L)
  private String failureURL;

  public static final String SERIALIZED_NAME_REMINDER = "reminder";
  @SerializedName(SERIALIZED_NAME_REMINDER)
  private ReminderDTO reminder;

  public static final String SERIALIZED_NAME_CUSTOM_ATTRIBUTES = "customAttributes";
  @SerializedName(SERIALIZED_NAME_CUSTOM_ATTRIBUTES)
  private List<CustomAttributeDTO> customAttributes = null;

  public static final String SERIALIZED_NAME_DROP_CATEGORY = "dropCategory";
  @SerializedName(SERIALIZED_NAME_DROP_CATEGORY)
  private String dropCategory;

  public static final String SERIALIZED_NAME_ENFORCE_PAY_METHOD = "enforcePayMethod";
  @SerializedName(SERIALIZED_NAME_ENFORCE_PAY_METHOD)
  private String enforcePayMethod;


  public PaymentLinkRequestDTO invoiceNumber(String invoiceNumber) {
    
    this.invoiceNumber = invoiceNumber;
    return this;
  }

   /**
   * It is used for identifying a payment link. This must be alphanumeric.
   * @return invoiceNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "INV8446471886220", value = "It is used for identifying a payment link. This must be alphanumeric.")

  public String getInvoiceNumber() {
    return invoiceNumber;
  }


  public void setInvoiceNumber(String invoiceNumber) {
    this.invoiceNumber = invoiceNumber;
  }


  public PaymentLinkRequestDTO isAmountFilledByCustomer(Boolean isAmountFilledByCustomer) {
    
    this.isAmountFilledByCustomer = isAmountFilledByCustomer;
    return this;
  }

   /**
   * This parameter contains any of the following values to specify whether it is an open invoices (when customer fills amount) or fixed amount  true-It is an open invoice where the customer can fill the amount. The subamount parameter must be null in this case  false-It is closed invoice and amount is fixed
   * @return isAmountFilledByCustomer
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "false", value = "This parameter contains any of the following values to specify whether it is an open invoices (when customer fills amount) or fixed amount  true-It is an open invoice where the customer can fill the amount. The subamount parameter must be null in this case  false-It is closed invoice and amount is fixed")

  public Boolean getIsAmountFilledByCustomer() {
    return isAmountFilledByCustomer;
  }


  public void setIsAmountFilledByCustomer(Boolean isAmountFilledByCustomer) {
    this.isAmountFilledByCustomer = isAmountFilledByCustomer;
  }


  public PaymentLinkRequestDTO subAmount(Double subAmount) {
    
    this.subAmount = subAmount;
    return this;
  }

   /**
   * Payment Amount.The value must be greater than or equal to 1
   * @return subAmount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1000", value = "Payment Amount.The value must be greater than or equal to 1")

  public Double getSubAmount() {
    return subAmount;
  }


  public void setSubAmount(Double subAmount) {
    this.subAmount = subAmount;
  }


  public PaymentLinkRequestDTO tax(Double tax) {
    
    this.tax = tax;
    return this;
  }

   /**
   *  tax amount for the payment transaction. This value must be greater than zero.
   * @return tax
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "10", value = " tax amount for the payment transaction. This value must be greater than zero.")

  public Double getTax() {
    return tax;
  }


  public void setTax(Double tax) {
    this.tax = tax;
  }


  public PaymentLinkRequestDTO shippingCharge(Double shippingCharge) {
    
    this.shippingCharge = shippingCharge;
    return this;
  }

   /**
   *  shipping charges for delivering the goods. This value must be greater than zero.
   * @return shippingCharge
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "25", value = " shipping charges for delivering the goods. This value must be greater than zero.")

  public Double getShippingCharge() {
    return shippingCharge;
  }


  public void setShippingCharge(Double shippingCharge) {
    this.shippingCharge = shippingCharge;
  }


  public PaymentLinkRequestDTO minAmountForCustomer(Double minAmountForCustomer) {
    
    this.minAmountForCustomer = minAmountForCustomer;
    return this;
  }

   /**
   *  minimum amount a customer needs to pay in case of partial payment.
   * @return minAmountForCustomer
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "800", value = " minimum amount a customer needs to pay in case of partial payment.")

  public Double getMinAmountForCustomer() {
    return minAmountForCustomer;
  }


  public void setMinAmountForCustomer(Double minAmountForCustomer) {
    this.minAmountForCustomer = minAmountForCustomer;
  }


  public PaymentLinkRequestDTO discount(Double discount) {
    
    this.discount = discount;
    return this;
  }

   /**
   * Get discount
   * @return discount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Double getDiscount() {
    return discount;
  }


  public void setDiscount(Double discount) {
    this.discount = discount;
  }


  public PaymentLinkRequestDTO adjustment(Double adjustment) {
    
    this.adjustment = adjustment;
    return this;
  }

   /**
   * Get adjustment
   * @return adjustment
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Double getAdjustment() {
    return adjustment;
  }


  public void setAdjustment(Double adjustment) {
    this.adjustment = adjustment;
  }


  public PaymentLinkRequestDTO smsConfirm(String smsConfirm) {
    
    this.smsConfirm = smsConfirm;
    return this;
  }

   /**
   * Get smsConfirm
   * @return smsConfirm
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getSmsConfirm() {
    return smsConfirm;
  }


  public void setSmsConfirm(String smsConfirm) {
    this.smsConfirm = smsConfirm;
  }


  public PaymentLinkRequestDTO description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * description or purpose of creating the.payment link.
   * @return description
  **/
  @ApiModelProperty(example = "Car Insurance Premium", required = true, value = "description or purpose of creating the.payment link.")

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public PaymentLinkRequestDTO source(String source) {
    
    this.source = source;
    return this;
  }

   /**
   * source of payment generation.
   * @return source
  **/
  @ApiModelProperty(example = "API", required = true, value = "source of payment generation.")

  public String getSource() {
    return source;
  }


  public void setSource(String source) {
    this.source = source;
  }


  public PaymentLinkRequestDTO isPartialPaymentAllowed(Boolean isPartialPaymentAllowed) {
    
    this.isPartialPaymentAllowed = isPartialPaymentAllowed;
    return this;
  }

   /**
   * Get isPartialPaymentAllowed
   * @return isPartialPaymentAllowed
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getIsPartialPaymentAllowed() {
    return isPartialPaymentAllowed;
  }


  public void setIsPartialPaymentAllowed(Boolean isPartialPaymentAllowed) {
    this.isPartialPaymentAllowed = isPartialPaymentAllowed;
  }


  public PaymentLinkRequestDTO currency(String currency) {
    
    this.currency = currency;
    return this;
  }

   /**
   * currency details
   * @return currency
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "INR", value = "currency details")

  public String getCurrency() {
    return currency;
  }


  public void setCurrency(String currency) {
    this.currency = currency;
  }


  public PaymentLinkRequestDTO maxPaymentsAllowed(Integer maxPaymentsAllowed) {
    
    this.maxPaymentsAllowed = maxPaymentsAllowed;
    return this;
  }

   /**
   * Get maxPaymentsAllowed
   * minimum: 1
   * @return maxPaymentsAllowed
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getMaxPaymentsAllowed() {
    return maxPaymentsAllowed;
  }


  public void setMaxPaymentsAllowed(Integer maxPaymentsAllowed) {
    this.maxPaymentsAllowed = maxPaymentsAllowed;
  }


  public PaymentLinkRequestDTO batchId(String batchId) {
    
    this.batchId = batchId;
    return this;
  }

   /**
   * Get batchId
   * @return batchId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getBatchId() {
    return batchId;
  }


  public void setBatchId(String batchId) {
    this.batchId = batchId;
  }


  public PaymentLinkRequestDTO expiryDate(String expiryDate) {
    
    this.expiryDate = expiryDate;
    return this;
  }

   /**
   * expiry date of the payment link (will be 365 days in all other cases).
   * @return expiryDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2012-11-21 22:11:11", value = "expiry date of the payment link (will be 365 days in all other cases).")

  public String getExpiryDate() {
    return expiryDate;
  }


  public void setExpiryDate(String expiryDate) {
    this.expiryDate = expiryDate;
  }


  public PaymentLinkRequestDTO scheduledFor(String scheduledFor) {
    
    this.scheduledFor = scheduledFor;
    return this;
  }

   /**
   * Get scheduledFor
   * @return scheduledFor
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getScheduledFor() {
    return scheduledFor;
  }


  public void setScheduledFor(String scheduledFor) {
    this.scheduledFor = scheduledFor;
  }


  public PaymentLinkRequestDTO viaEmail(Boolean viaEmail) {
    
    this.viaEmail = viaEmail;
    return this;
  }

   /**
   * specify whether to directly send an email to customer upon payment link generation or late
   * @return viaEmail
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "specify whether to directly send an email to customer upon payment link generation or late")

  public Boolean getViaEmail() {
    return viaEmail;
  }


  public void setViaEmail(Boolean viaEmail) {
    this.viaEmail = viaEmail;
  }


  public PaymentLinkRequestDTO viaSms(Boolean viaSms) {
    
    this.viaSms = viaSms;
    return this;
  }

   /**
   * specify whether to directly send as SMS to customer upon payment link generation or later
   * @return viaSms
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "specify whether to directly send as SMS to customer upon payment link generation or later")

  public Boolean getViaSms() {
    return viaSms;
  }


  public void setViaSms(Boolean viaSms) {
    this.viaSms = viaSms;
  }


  public PaymentLinkRequestDTO customer(CustomerDTO customer) {
    
    this.customer = customer;
    return this;
  }

   /**
   * Get customer
   * @return customer
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public CustomerDTO getCustomer() {
    return customer;
  }


  public void setCustomer(CustomerDTO customer) {
    this.customer = customer;
  }


  public PaymentLinkRequestDTO udf(UdfDTO udf) {
    
    this.udf = udf;
    return this;
  }

   /**
   * Get udf
   * @return udf
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public UdfDTO getUdf() {
    return udf;
  }


  public void setUdf(UdfDTO udf) {
    this.udf = udf;
  }


  public PaymentLinkRequestDTO address(AddressDTO address) {
    
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public AddressDTO getAddress() {
    return address;
  }


  public void setAddress(AddressDTO address) {
    this.address = address;
  }


  public PaymentLinkRequestDTO emailTemplateName(String emailTemplateName) {
    
    this.emailTemplateName = emailTemplateName;
    return this;
  }

   /**
   * Get emailTemplateName
   * @return emailTemplateName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getEmailTemplateName() {
    return emailTemplateName;
  }


  public void setEmailTemplateName(String emailTemplateName) {
    this.emailTemplateName = emailTemplateName;
  }


  public PaymentLinkRequestDTO smsTemplateName(String smsTemplateName) {
    
    this.smsTemplateName = smsTemplateName;
    return this;
  }

   /**
   * Get smsTemplateName
   * @return smsTemplateName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getSmsTemplateName() {
    return smsTemplateName;
  }


  public void setSmsTemplateName(String smsTemplateName) {
    this.smsTemplateName = smsTemplateName;
  }


  public PaymentLinkRequestDTO validationPeriod(String validationPeriod) {
    
    this.validationPeriod = validationPeriod;
    return this;
  }

   /**
   * Get validationPeriod
   * @return validationPeriod
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getValidationPeriod() {
    return validationPeriod;
  }


  public void setValidationPeriod(String validationPeriod) {
    this.validationPeriod = validationPeriod;
  }


  public PaymentLinkRequestDTO timeUnit(String timeUnit) {
    
    this.timeUnit = timeUnit;
    return this;
  }

   /**
   * Get timeUnit
   * @return timeUnit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getTimeUnit() {
    return timeUnit;
  }


  public void setTimeUnit(String timeUnit) {
    this.timeUnit = timeUnit;
  }


  public PaymentLinkRequestDTO notes(String notes) {
    
    this.notes = notes;
    return this;
  }

   /**
   * Get notes
   * @return notes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getNotes() {
    return notes;
  }


  public void setNotes(String notes) {
    this.notes = notes;
  }


  public PaymentLinkRequestDTO successURL(String successURL) {
    
    this.successURL = successURL;
    return this;
  }

   /**
   * Get successURL
   * @return successURL
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getSuccessURL() {
    return successURL;
  }


  public void setSuccessURL(String successURL) {
    this.successURL = successURL;
  }


  public PaymentLinkRequestDTO failureURL(String failureURL) {
    
    this.failureURL = failureURL;
    return this;
  }

   /**
   * Get failureURL
   * @return failureURL
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getFailureURL() {
    return failureURL;
  }


  public void setFailureURL(String failureURL) {
    this.failureURL = failureURL;
  }


  public PaymentLinkRequestDTO reminder(ReminderDTO reminder) {
    
    this.reminder = reminder;
    return this;
  }

   /**
   * Get reminder
   * @return reminder
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ReminderDTO getReminder() {
    return reminder;
  }


  public void setReminder(ReminderDTO reminder) {
    this.reminder = reminder;
  }


  public PaymentLinkRequestDTO customAttributes(List<CustomAttributeDTO> customAttributes) {
    
    this.customAttributes = customAttributes;
    return this;
  }

  public PaymentLinkRequestDTO addCustomAttributesItem(CustomAttributeDTO customAttributesItem) {
    if (this.customAttributes == null) {
      this.customAttributes = new ArrayList<CustomAttributeDTO>();
    }
    this.customAttributes.add(customAttributesItem);
    return this;
  }

   /**
   * Get customAttributes
   * @return customAttributes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<CustomAttributeDTO> getCustomAttributes() {
    return customAttributes;
  }


  public void setCustomAttributes(List<CustomAttributeDTO> customAttributes) {
    this.customAttributes = customAttributes;
  }


  public PaymentLinkRequestDTO dropCategory(String dropCategory) {
    
    this.dropCategory = dropCategory;
    return this;
  }

   /**
   * Get dropCategory
   * @return dropCategory
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getDropCategory() {
    return dropCategory;
  }


  public void setDropCategory(String dropCategory) {
    this.dropCategory = dropCategory;
  }


  public PaymentLinkRequestDTO enforcePayMethod(String enforcePayMethod) {
    
    this.enforcePayMethod = enforcePayMethod;
    return this;
  }

   /**
   * Get enforcePayMethod
   * @return enforcePayMethod
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getEnforcePayMethod() {
    return enforcePayMethod;
  }


  public void setEnforcePayMethod(String enforcePayMethod) {
    this.enforcePayMethod = enforcePayMethod;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentLinkRequestDTO paymentLinkRequestDTO = (PaymentLinkRequestDTO) o;
    return Objects.equals(this.invoiceNumber, paymentLinkRequestDTO.invoiceNumber) &&
        Objects.equals(this.isAmountFilledByCustomer, paymentLinkRequestDTO.isAmountFilledByCustomer) &&
        Objects.equals(this.subAmount, paymentLinkRequestDTO.subAmount) &&
        Objects.equals(this.tax, paymentLinkRequestDTO.tax) &&
        Objects.equals(this.shippingCharge, paymentLinkRequestDTO.shippingCharge) &&
        Objects.equals(this.minAmountForCustomer, paymentLinkRequestDTO.minAmountForCustomer) &&
        Objects.equals(this.discount, paymentLinkRequestDTO.discount) &&
        Objects.equals(this.adjustment, paymentLinkRequestDTO.adjustment) &&
        Objects.equals(this.smsConfirm, paymentLinkRequestDTO.smsConfirm) &&
        Objects.equals(this.description, paymentLinkRequestDTO.description) &&
        Objects.equals(this.source, paymentLinkRequestDTO.source) &&
        Objects.equals(this.isPartialPaymentAllowed, paymentLinkRequestDTO.isPartialPaymentAllowed) &&
        Objects.equals(this.currency, paymentLinkRequestDTO.currency) &&
        Objects.equals(this.maxPaymentsAllowed, paymentLinkRequestDTO.maxPaymentsAllowed) &&
        Objects.equals(this.batchId, paymentLinkRequestDTO.batchId) &&
        Objects.equals(this.expiryDate, paymentLinkRequestDTO.expiryDate) &&
        Objects.equals(this.scheduledFor, paymentLinkRequestDTO.scheduledFor) &&
        Objects.equals(this.viaEmail, paymentLinkRequestDTO.viaEmail) &&
        Objects.equals(this.viaSms, paymentLinkRequestDTO.viaSms) &&
        Objects.equals(this.customer, paymentLinkRequestDTO.customer) &&
        Objects.equals(this.udf, paymentLinkRequestDTO.udf) &&
        Objects.equals(this.address, paymentLinkRequestDTO.address) &&
        Objects.equals(this.emailTemplateName, paymentLinkRequestDTO.emailTemplateName) &&
        Objects.equals(this.smsTemplateName, paymentLinkRequestDTO.smsTemplateName) &&
        Objects.equals(this.validationPeriod, paymentLinkRequestDTO.validationPeriod) &&
        Objects.equals(this.timeUnit, paymentLinkRequestDTO.timeUnit) &&
        Objects.equals(this.notes, paymentLinkRequestDTO.notes) &&
        Objects.equals(this.successURL, paymentLinkRequestDTO.successURL) &&
        Objects.equals(this.failureURL, paymentLinkRequestDTO.failureURL) &&
        Objects.equals(this.reminder, paymentLinkRequestDTO.reminder) &&
        Objects.equals(this.customAttributes, paymentLinkRequestDTO.customAttributes) &&
        Objects.equals(this.dropCategory, paymentLinkRequestDTO.dropCategory) &&
        Objects.equals(this.enforcePayMethod, paymentLinkRequestDTO.enforcePayMethod);
  }

  @Override
  public int hashCode() {
    return Objects.hash(invoiceNumber, isAmountFilledByCustomer, subAmount, tax, shippingCharge, minAmountForCustomer, discount, adjustment, smsConfirm, description, source, isPartialPaymentAllowed, currency, maxPaymentsAllowed, batchId, expiryDate, scheduledFor, viaEmail, viaSms, customer, udf, address, emailTemplateName, smsTemplateName, validationPeriod, timeUnit, notes, successURL, failureURL, reminder, customAttributes, dropCategory, enforcePayMethod);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentLinkRequestDTO {\n");
    sb.append("    invoiceNumber: ").append(toIndentedString(invoiceNumber)).append("\n");
    sb.append("    isAmountFilledByCustomer: ").append(toIndentedString(isAmountFilledByCustomer)).append("\n");
    sb.append("    subAmount: ").append(toIndentedString(subAmount)).append("\n");
    sb.append("    tax: ").append(toIndentedString(tax)).append("\n");
    sb.append("    shippingCharge: ").append(toIndentedString(shippingCharge)).append("\n");
    sb.append("    minAmountForCustomer: ").append(toIndentedString(minAmountForCustomer)).append("\n");
    sb.append("    discount: ").append(toIndentedString(discount)).append("\n");
    sb.append("    adjustment: ").append(toIndentedString(adjustment)).append("\n");
    sb.append("    smsConfirm: ").append(toIndentedString(smsConfirm)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("    isPartialPaymentAllowed: ").append(toIndentedString(isPartialPaymentAllowed)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    maxPaymentsAllowed: ").append(toIndentedString(maxPaymentsAllowed)).append("\n");
    sb.append("    batchId: ").append(toIndentedString(batchId)).append("\n");
    sb.append("    expiryDate: ").append(toIndentedString(expiryDate)).append("\n");
    sb.append("    scheduledFor: ").append(toIndentedString(scheduledFor)).append("\n");
    sb.append("    viaEmail: ").append(toIndentedString(viaEmail)).append("\n");
    sb.append("    viaSms: ").append(toIndentedString(viaSms)).append("\n");
    sb.append("    customer: ").append(toIndentedString(customer)).append("\n");
    sb.append("    udf: ").append(toIndentedString(udf)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    emailTemplateName: ").append(toIndentedString(emailTemplateName)).append("\n");
    sb.append("    smsTemplateName: ").append(toIndentedString(smsTemplateName)).append("\n");
    sb.append("    validationPeriod: ").append(toIndentedString(validationPeriod)).append("\n");
    sb.append("    timeUnit: ").append(toIndentedString(timeUnit)).append("\n");
    sb.append("    notes: ").append(toIndentedString(notes)).append("\n");
    sb.append("    successURL: ").append(toIndentedString(successURL)).append("\n");
    sb.append("    failureURL: ").append(toIndentedString(failureURL)).append("\n");
    sb.append("    reminder: ").append(toIndentedString(reminder)).append("\n");
    sb.append("    customAttributes: ").append(toIndentedString(customAttributes)).append("\n");
    sb.append("    dropCategory: ").append(toIndentedString(dropCategory)).append("\n");
    sb.append("    enforcePayMethod: ").append(toIndentedString(enforcePayMethod)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

