/*
 * Hub Token
 * Generate Token
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.StaticFieldDTO;

/**
 * StatusOrExpiryDTO
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-06-07T19:17:40.573+05:30[Asia/Kolkata]")
public class StatusOrExpiryDTO {
  public static final String SERIALIZED_NAME_ACTIVE = "active";
  @SerializedName(SERIALIZED_NAME_ACTIVE)
  private Boolean active;

  public static final String SERIALIZED_NAME_EXPIRY = "expiry";
  @SerializedName(SERIALIZED_NAME_EXPIRY)
  private String expiry;

  public static final String SERIALIZED_NAME_STATIC_FIELDS = "staticFields";
  @SerializedName(SERIALIZED_NAME_STATIC_FIELDS)
  private StaticFieldDTO staticFields;


  public StatusOrExpiryDTO active(Boolean active) {
    
    this.active = active;
    return this;
  }

   /**
   * Get active
   * @return active
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getActive() {
    return active;
  }


  public void setActive(Boolean active) {
    this.active = active;
  }


  public StatusOrExpiryDTO expiry(String expiry) {
    
    this.expiry = expiry;
    return this;
  }

   /**
   * Get expiry
   * @return expiry
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getExpiry() {
    return expiry;
  }


  public void setExpiry(String expiry) {
    this.expiry = expiry;
  }


  public StatusOrExpiryDTO staticFields(StaticFieldDTO staticFields) {
    
    this.staticFields = staticFields;
    return this;
  }

   /**
   * Get staticFields
   * @return staticFields
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public StaticFieldDTO getStaticFields() {
    return staticFields;
  }


  public void setStaticFields(StaticFieldDTO staticFields) {
    this.staticFields = staticFields;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StatusOrExpiryDTO statusOrExpiryDTO = (StatusOrExpiryDTO) o;
    return Objects.equals(this.active, statusOrExpiryDTO.active) &&
        Objects.equals(this.expiry, statusOrExpiryDTO.expiry) &&
        Objects.equals(this.staticFields, statusOrExpiryDTO.staticFields);
  }

  @Override
  public int hashCode() {
    return Objects.hash(active, expiry, staticFields);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StatusOrExpiryDTO {\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    expiry: ").append(toIndentedString(expiry)).append("\n");
    sb.append("    staticFields: ").append(toIndentedString(staticFields)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

