/*
 * Hub Token
 * Generate Token
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * UdfDTO
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-06-07T19:17:40.573+05:30[Asia/Kolkata]")
public class UdfDTO {
  public static final String SERIALIZED_NAME_UDF1 = "udf1";
  @SerializedName(SERIALIZED_NAME_UDF1)
  private String udf1;

  public static final String SERIALIZED_NAME_UDF2 = "udf2";
  @SerializedName(SERIALIZED_NAME_UDF2)
  private String udf2;

  public static final String SERIALIZED_NAME_UDF3 = "udf3";
  @SerializedName(SERIALIZED_NAME_UDF3)
  private String udf3;

  public static final String SERIALIZED_NAME_UDF4 = "udf4";
  @SerializedName(SERIALIZED_NAME_UDF4)
  private String udf4;

  public static final String SERIALIZED_NAME_UDF5 = "udf5";
  @SerializedName(SERIALIZED_NAME_UDF5)
  private String udf5;


  public UdfDTO udf1(String udf1) {
    
    this.udf1 = udf1;
    return this;
  }

   /**
   * Get udf1
   * @return udf1
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getUdf1() {
    return udf1;
  }


  public void setUdf1(String udf1) {
    this.udf1 = udf1;
  }


  public UdfDTO udf2(String udf2) {
    
    this.udf2 = udf2;
    return this;
  }

   /**
   * Get udf2
   * @return udf2
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getUdf2() {
    return udf2;
  }


  public void setUdf2(String udf2) {
    this.udf2 = udf2;
  }


  public UdfDTO udf3(String udf3) {
    
    this.udf3 = udf3;
    return this;
  }

   /**
   * Get udf3
   * @return udf3
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getUdf3() {
    return udf3;
  }


  public void setUdf3(String udf3) {
    this.udf3 = udf3;
  }


  public UdfDTO udf4(String udf4) {
    
    this.udf4 = udf4;
    return this;
  }

   /**
   * Get udf4
   * @return udf4
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getUdf4() {
    return udf4;
  }


  public void setUdf4(String udf4) {
    this.udf4 = udf4;
  }


  public UdfDTO udf5(String udf5) {
    
    this.udf5 = udf5;
    return this;
  }

   /**
   * Get udf5
   * @return udf5
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getUdf5() {
    return udf5;
  }


  public void setUdf5(String udf5) {
    this.udf5 = udf5;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UdfDTO udfDTO = (UdfDTO) o;
    return Objects.equals(this.udf1, udfDTO.udf1) &&
        Objects.equals(this.udf2, udfDTO.udf2) &&
        Objects.equals(this.udf3, udfDTO.udf3) &&
        Objects.equals(this.udf4, udfDTO.udf4) &&
        Objects.equals(this.udf5, udfDTO.udf5);
  }

  @Override
  public int hashCode() {
    return Objects.hash(udf1, udf2, udf3, udf4, udf5);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UdfDTO {\n");
    sb.append("    udf1: ").append(toIndentedString(udf1)).append("\n");
    sb.append("    udf2: ").append(toIndentedString(udf2)).append("\n");
    sb.append("    udf3: ").append(toIndentedString(udf3)).append("\n");
    sb.append("    udf4: ").append(toIndentedString(udf4)).append("\n");
    sb.append("    udf5: ").append(toIndentedString(udf5)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

